# Copyright (C) 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

# Inherit from oneplus sm8650-common
include device/oneplus/sm8650-common/BoardConfigCommon.mk

DEVICE_PATH := device/oneplus/13r

# Assert
TARGET_OTA_ASSERT_DEVICE := 13r

# Display
TARGET_SCREEN_DENSITY := 510
TARGET_HAS_HDR_DISPLAY := true
TARGET_HAS_WIDE_COLOR_DISPLAY := true

# Kernel
TARGET_KERNEL_CONFIG := oneplus_13r_defconfig
BOARD_KERNEL_CMDLINE += androidboot.hardware=qcom
BOARD_KERNEL_CMDLINE += androidboot.memcg=1
BOARD_KERNEL_CMDLINE += androidboot.usbcontroller=a600000.dwc3

# Kernel modules
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(strip $(shell cat $(DEVICE_PATH)/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD := $(strip $(shell cat $(DEVICE_PATH)/modules.load.recovery))

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 201326592
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 201326592
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 201326592
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := oneplus_dynamic_partitions
BOARD_ONEPLUS_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_ONEPLUS_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor odm vendor_dlkm odm_dlkm

# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Recovery
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 103

# Security patch level
VENDOR_SECURITY_PATCH := 2025-03-01

# SELinux
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
PRODUCT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private

# Touch
SOONG_CONFIG_NAMESPACES += OPLUS_LINEAGE_TOUCH_HAL
SOONG_CONFIG_OPLUS_LINEAGE_TOUCH_HAL := INCLUDE_DIR
SOONG_CONFIG_OPLUS_LINEAGE_TOUCH_HAL_INCLUDE_DIR := $(DEVICE_PATH)/touch/include

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# Alert Slider
SOONG_CONFIG_NAMESPACES += ONEPLUS_TRI_STATE_KEY
SOONG_CONFIG_ONEPLUS_TRI_STATE_KEY := INCLUDE_DIR
SOONG_CONFIG_ONEPLUS_TRI_STATE_KEY_INCLUDE_DIR := $(DEVICE_PATH)/tri_state_key/include

# SUPERVOOC Charging
SOONG_CONFIG_NAMESPACES += ONEPLUS_CHARGING
SOONG_CONFIG_ONEPLUS_CHARGING := INCLUDE_DIR
SOONG_CONFIG_ONEPLUS_CHARGING_INCLUDE_DIR := $(DEVICE_PATH)/charging/include

# Fingerprint
SOONG_CONFIG_NAMESPACES += ONEPLUS_FINGERPRINT
SOONG_CONFIG_ONEPLUS_FINGERPRINT := INCLUDE_DIR
SOONG_CONFIG_ONEPLUS_FINGERPRINT_INCLUDE_DIR := $(DEVICE_PATH)/fingerprint/include

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    odm \
    product \
    system \
    system_ext \
    vbmeta \
    vbmeta_system \
    vendor \
    vendor_boot \
    vendor_kernel_boot

# Inherit the proprietary files
include vendor/oneplus/13r/BoardConfigVendor.mk 