#ifndef BDROID_BUILDCFG_H
#define BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME "OnePlus 13R"
#define BTA_DISABLE_DELAY 1000
#define BT_CLEAN_TURN_ON_DISABLED TRUE
#define BTA_DM_COD {0x1C, 0x01, 0x00}
#define BTA_DM_BD_NAME "OnePlus 13R"

// BLE and WBS Support
#define BLE_VND_INCLUDED TRUE
#define BTM_WBS_INCLUDED TRUE
#define BTIF_HF_WBS_PREFERRED TRUE

// A2DP Support
#define BTA_AV_SINK_INCLUDED TRUE
#define BTA_AV_SOURCE_INCLUDED TRUE
#define BTA_AV_MULTI_SOURCE_INCLUDED TRUE
#define BTA_AV_MULTI_SINK_INCLUDED TRUE

#endif // BDROID_BUILDCFG_H
